### ISSUE TITLE
Docs are offline

### ISSUE THREAD

**Issue by jonas-schievink** [ogham/rust-pad#2]
The link to the docs 404s now

**Comment by ogham** [comment]
It does. I didn't know people still use this crate! Does it do something that the built-in `format!` macro doesn't?

**Comment by jonas-schievink** [comment]
I'm not sure, it looks a bit more flexible at least. I only stumbled upon this because [`cargo-edit`](https://github.com/killercup/cargo-edit) uses it :)

**Comment by ogham** [comment]
huh! I had no idea. I need to generate the docs later today (did an ansi-term release) so will put this one back. thanks for bringing it to my attention!
